#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Disable auto build on commit because I will auto build it on the server
# # Normal project build #
# ng build;

# # Stage compilation folder #
# git add -A docs;
